### PR TITLE
Sitemap improvements

### PR DESCRIPTION
**Pull request by ruflin**
The current sitemap is built based on the sitemap.xml file. The current sitemap implementation does not work properly with the baseurl and url configuration. Instead of "fixing" the file I suggest to directly use the sitemap plugin provided by Jekyll which is under active development: https://github.com/jekyll/jekyll-sitemap 

This pull request introduces this change.

### CODE REVIEW

**Comment by chrisanthropic** [comment]
Changing the baseurl and url settings actually breaks a lot of things - sitemap, feed, blog links, etc.

This brings up a good point that I need to go back and make those changes, but I can't merge this without breaking a lot of other things.

**Comment by ruflin** [comment]
On my side everything seems to work as expected except the atom feed was broken. I fixed this now also by replacing it with the plugin. Let me know what else is broken so I can fix it and add it to the pull request.

**Comment by chrisanthropic** [comment]
Nope, you're right. It was an issue with some custom tweaks I'd made locally to my rakefile. Thanks for the updates.

I will say that my original plan was to include as few pieces of external code and plugins as possible but that was mostly stubbornness and using the plugins is a good call.

Merging now, thanks.

**Comment by ruflin** [comment]
I fully understand the drive to do it yourself ;-) But I think at this point it makes it easier to maintain. Thanks for merging.

**Pull request merged**
